services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Shopsys\ArticleFeed\PersooBundle\:
        resource: '../../*'

    Shopsys\ArticleFeed\PersooBundle\PersooArticleFeed:
        tags:
            - { name: shopsys.feed, hours: '*', minutes: '30' }
